/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.io.File;
import java.util.Queue;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import Modelo.Boleta;
import Servicio.ExcelReaderMasivo;
import Servicio.GeneradorTXTMasivo;

/**
 *
 * @author DIEGO
 */
public class Generador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Generador.class.getName());

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
        Agregar1.setOpaque(false);
        Agregar1.setContentAreaFilled(false);
        Agregar1.setBorderPainted(false);
        Agregar1.setFocusPainted(false);
        Agregar2.setOpaque(false);
        Agregar2.setContentAreaFilled(false);
        Agregar2.setBorderPainted(false);
        Agregar2.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        Agregar1 = new javax.swing.JButton();
        Agregar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRznSocial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNomComer = new javax.swing.JTextField();
        btnGenerarMasivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(191, 191, 189));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "RUTAS DE ARCHIVOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(13, 13, 13));
        jLabel1.setText("RUTA DEL ARCHIVO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 160, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(13, 13, 13));
        jLabel2.setText("DESTINO DEL TXT:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 25));
        jPanel1.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 250, 40));

        txtDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDestino.setForeground(new java.awt.Color(13, 13, 13));
        jPanel1.add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 74, 250, 40));

        Agregar1.setBackground(new java.awt.Color(191, 191, 189));
        Agregar1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Agregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icono (3).png"))); // NOI18N
        Agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 26, 60, 40));

        Agregar2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Agregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icono (3).png"))); // NOI18N
        Agregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar2ActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 60, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 150));

        jPanel2.setBackground(new java.awt.Color(191, 191, 189));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "DATOS DEL EMISOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(13, 13, 13));
        jLabel3.setText("RUC:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 160, 25));

        txtRuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRuc.setForeground(new java.awt.Color(13, 13, 13));
        jPanel2.add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 250, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(13, 13, 13));
        jLabel4.setText("RAZON SOCIAL:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 160, 25));

        txtRznSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRznSocial.setForeground(new java.awt.Color(13, 13, 13));
        jPanel2.add(txtRznSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 250, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(13, 13, 13));
        jLabel5.setText("NOMBRE COMERCIAL: ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 160, 25));

        txtNomComer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomComer.setForeground(new java.awt.Color(13, 13, 13));
        jPanel2.add(txtNomComer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 250, 40));

        btnGenerarMasivo.setBackground(new java.awt.Color(242, 242, 242));
        btnGenerarMasivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGenerarMasivo.setText("GENERAR MASIVO");
        btnGenerarMasivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarMasivoActionPerformed(evt);
            }
        });
        jPanel2.add(btnGenerarMasivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 210, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 630, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar1ActionPerformed
        // TODO add your handling code here:
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            System.getLogger(Generador.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        String user = System.getProperty("user.home");
        File descargas = new File(user + "/Downloads");
        JFileChooser chooser = new JFileChooser(descargas);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos Excel", "xlsx", "xlsm"));
        chooser.setAcceptAllFileFilterUsed(false);
        int option = chooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            String ruta = chooser.getSelectedFile().getAbsolutePath();
            txtRuta.setText(ruta);
        }
    }//GEN-LAST:event_Agregar1ActionPerformed

    private void Agregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar2ActionPerformed
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            System.getLogger(Generador.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        String user = System.getProperty("user.home");
        File descargas = new File(user + "/Downloads");
        JFileChooser chooser = new JFileChooser(descargas);
        chooser.setDialogTitle("Seleccionar carpeta de destino");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        int opcion = chooser.showOpenDialog(this);

        if (opcion == JFileChooser.APPROVE_OPTION) {
            String carpeta = chooser.getSelectedFile().getAbsolutePath();
            txtDestino.setText(carpeta);

        }
    }//GEN-LAST:event_Agregar2ActionPerformed

    private void btnGenerarMasivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarMasivoActionPerformed
        // TODO add your handling code here:
        var ruc = txtRuc.getText();
        var rznSocial = txtRznSocial.getText();
        var nomComercio = txtNomComer.getText();
        String rutaExcel = txtRuta.getText().trim();
        String rutaSalida = txtDestino.getText().trim();

        try{
            Queue<Boleta> cola = ExcelReaderMasivo.leerBoletas(rutaExcel);
            for (Boleta b : cola) {
                b.setRutEmis(ruc);
                b.setRazoSocEmi(rznSocial);
                b.setNomComer(nomComercio);
            }
            GeneradorTXTMasivo.validarCola(cola, rutaSalida);
            JOptionPane.showMessageDialog(null, "ARCHIVOS GENERADOS CON EXITO");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR AL GENERAR LOS ARCHIVOS"
                + e.getMessage());
        }
    }//GEN-LAST:event_btnGenerarMasivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Generador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar1;
    private javax.swing.JButton Agregar2;
    private javax.swing.JButton btnGenerarMasivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtNomComer;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextField txtRznSocial;
    // End of variables declaration//GEN-END:variables
}
